# Bag of words

In [6]:
import pandas as pd
import numpy as np

In [1]:
x = ['which book is this','this is book and this is math']

In [2]:
from sklearn.feature_extraction.text import CountVectorizer

In [3]:
cv = CountVectorizer()
count = cv.fit_transform(x)

In [4]:
count.toarray()

array([[0, 1, 1, 0, 1, 1],
       [1, 1, 2, 1, 2, 0]])

In [5]:
cv.get_feature_names()

['and', 'book', 'is', 'math', 'this', 'which']

In [10]:
bow = pd.DataFrame(count.toarray(),columns = cv.get_feature_names())
bow

and  book  is  math  this  which
0    0     1   1     0     1      1
1    1     1   2     1     2      0

In [29]:
# bow.drop(columns = 'sum',inplace = True)

# Calculate the term frequency

In [30]:
bow.shape

(2, 6)

2 rows and 6 tokens

In [31]:
tf = bow.copy()

In [32]:
tf

and  book  is  math  this  which
0    0     1   1     0     1      1
1    1     1   2     1     2      0

In [33]:
# for i in tf.iterrows():
#     print(i.index)

In [34]:
for index,row in enumerate(tf.iterrows()):
    for col in row[1].index:
        tf.loc[index,col] = tf.loc[index,col]/sum(row[1].values)

In [35]:
tf

and      book        is      math      this  which
0  0.000000  0.250000  0.250000  0.000000  0.250000   0.25
1  0.142857  0.142857  0.285714  0.142857  0.285714   0.00

# Inverse Document Frequency IDF

idf = log((1+N)/(n+1)) + 1

for 
- N: total number of rows regardless of the appearence of the word.
- and n: number of rows in which the word was presented

In [36]:
bow

and  book  is  math  this  which
0    0     1   1     0     1      1
1    1     1   2     1     2      0

In [61]:
for i in bow.index:
    print(i)

0
1


In [73]:
idf = bow.copy()

idf = idf.astype('bool')
        

In [74]:
idf

and  book    is   math  this  which
0  False  True  True  False  True   True
1   True  True  True   True  True  False

In [75]:
cols = []

for i in idf.columns:
    cols.append(idf[i].sum())

In [76]:
cols

[1, 2, 2, 1, 2, 1]

In [77]:
for i in range(len(cols)):
    cols[i] = np.log((1 + bow.shape[0])/(1 + cols[i])) + 1

In [78]:
cols

[1.4054651081081644, 1.0, 1.0, 1.4054651081081644, 1.0, 1.4054651081081644]

In [79]:
idf = cols.copy()
idf = np.array(idf)
idf

array([1.40546511, 1.        , 1.        , 1.40546511, 1.        ,
       1.40546511])

This is the inverse document frequency of our tokens

# Calculate TFIDF (TF * IDF) using Scikit-learn

In [80]:
from sklearn.feature_extraction.text import TfidfVectorizer as tfv

In [81]:
x

['which book is this', 'this is book and this is math']

In [82]:
tfidf = tfv()
X = tfidf.fit_transform(x)
X

<2x6 sparse matrix of type '<class 'numpy.float64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [83]:
X.toarray()

array([[0.        , 0.44832087, 0.44832087, 0.        , 0.44832087,
        0.63009934],
       [0.39054766, 0.27787788, 0.55575576, 0.39054766, 0.55575576,
        0.        ]])

This is the tfidf array of our tokens

In [85]:
tfidf.idf_ #inverse document frequency

array([1.40546511, 1.        , 1.        , 1.40546511, 1.        ,
       1.40546511])